drop table if exists messages;
drop table if exists horaires_restaurants;
drop table if exists reservations;
drop table if exists commandes_produits;
drop table if exists commandes;
drop table if exists produits_cartes;
drop table if exists produits;
drop table if exists tableres;
drop table if exists utilisateurs;
drop table if exists categories;
drop table if exists restaurants;
drop table if exists cartes;
drop table if exists horaires;


create table cartes (id int   not null, libelle varchar(255), primary key (id));
create table categories (id int   not null, libelle varchar(255), primary key (id));
create table commandes (id int   not null, id_table int, heure datetime2(6), statut varchar(255), primary key (id));
create table commandes_produits (id_commande int not null, id_produit int not null);
create table horaires (heure_fermeture time, heure_ouverture time, id int   not null, jour varchar(255), primary key (id));
create table horaires_restaurants (id_horaire int not null, id_restaurant int not null);
create table messages (id int   not null, id_restaurant int, id_utilisateur int, contenu varchar(255), sujet varchar(255), primary key (id));
create table produits (id int   not null, id_categorie int, prix float(24) not null, description varchar(255), nom varchar(255), primary key (id));
create table produits_cartes (id_carte int not null, id_produit int not null);
create table reservations (date_res date, heure time, id int   not null, id_restaurant int, id_table int, id_utilisateur int, nb_personnes int not null, commentaire varchar(255), statut varchar(255), primary key (id));
create table restaurants (id int   not null, id_carte int, adresse varchar(255), cpo varchar(255), nom varchar(255), ville varchar(255), primary key (id));
create table tableres (id int   not null, id_restaurant int, nombre_places int not null, numero_table int not null, statut varchar(255), primary key (id));
create table utilisateurs (id int   not null, is_admin bit, email varchar(255), mot_de_passe varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), primary key (id));
create unique nonclustered index UK_i8mhg2r5fxqoo4xljqj1pnggx on commandes (id_table) where id_table is not null;
alter table commandes add constraint FKmkpkp1ytuukrpsi5lc7rka55a foreign key (id_table) references tableres;
alter table commandes_produits add constraint FK3ql8gc2sygtlx7dj9vtj6ak36 foreign key (id_produit) references produits;
alter table commandes_produits add constraint FK83dnwqrng5tdmc1wtxubushlr foreign key (id_commande) references commandes;
alter table horaires_restaurants add constraint FKdu4y2cu2rkj0tv7nh2r23m51n foreign key (id_horaire) references horaires;
alter table horaires_restaurants add constraint FKqfqbyy0byg8dkwevcw75hcypr foreign key (id_restaurant) references restaurants;
alter table messages add constraint FK6h8fh0iarfk8rgn2rupovex85 foreign key (id_restaurant) references restaurants;
alter table messages add constraint FKjua4nts9ny5wfy6b6bg8pv1dl foreign key (id_utilisateur) references utilisateurs;
alter table produits add constraint FKoxko2iw93mgoixwrkniqq11k6 foreign key (id_categorie) references categories;
alter table produits_cartes add constraint FKkjeykeglgdl6cmnsa4glivk70 foreign key (id_carte) references cartes;
alter table produits_cartes add constraint FKp7qwgxg210070l06eihfwg3ji foreign key (id_produit) references produits;
alter table reservations add constraint FKl9l6hgfk3sa87r0w4abh9dns8 foreign key (id_restaurant) references restaurants;
alter table reservations add constraint FKg71q6151pwkabpm2s0cl1n07o foreign key (id_table) references tableres;
alter table reservations add constraint FKb1gh00q44dhw24wajyfrwmlnt foreign key (id_utilisateur) references utilisateurs;
alter table restaurants add constraint FKk9qa5r3rt2kswq2ywb5jerbkj foreign key (id_carte) references cartes;
alter table tableres add constraint FKfqh1o7nt6q5fw80u90hvd2okh foreign key (id_restaurant) references restaurants;